# Generated by Django 3.0.8 on 2020-08-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
