# Generated by Django 3.0.8 on 2020-08-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_education_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('email', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('facebook', models.CharField(blank=True, max_length=250, null=True)),
                ('instagram', models.CharField(blank=True, max_length=250, null=True)),
                ('linkedid', models.CharField(blank=True, max_length=250, null=True)),
                ('github', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
