# Generated by Django 3.0.8 on 2020-08-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0007_auto_20200816_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='linkedid',
            new_name='linkedin',
        ),
    ]
